service: TWProject-Server

provider:
  name: aws
  runtime: nodejs10.x
  memorySize: 2048 # Maxixmum size, type Megabytes
  stage: dev
  region: us-east-2

functions:
  twmomoFunc:
    handler: index.handler
    events:
      - http:
          path: /login
          method: post
      - http:
          path: /register
          method: post
      - http:
          path: /twmomo/mysql/query
          method: post
      - http:
          path: /{proxy+}
          method: get

plugins:
  - serverless-prune-plugin
