service: TWProject-Server

provider:
  name: aws
  runtime: nodejs10.x
  memorySize: 512 # Maxixmum size, type Megabytes
  stage: dev
  region: us-east-1

functions:
  twmomoFunc:
    handler: index.handler
    events:
      - http:
          path: /register
          method: get
      - http:
          path: /{proxy+}
          method: get

plugins:
  - serverless-prune-plugin
