service: TWProject-Server

provider:
  name: aws
  runtime: nodejs10.x
  memorySize: 2048 # Maxixmum size, type Megabytes
  stage: dev
  region: us-east-2

functions:
  twmomoFunc:
    handler: index.handler
    events:
      - http:
          path: /login
          method: post
      - http:
          path: /register
          method: post
      - http:
          path: /register/detail
          method: post
      - http:
          path: /logging
          method: post
      - http:
          path: /concern/category
          method: post
      - http:
          path: /store/review/stars
          method: post
      - http:
          path: /store/review/comment
          method: post
      - http:
          path: /store/review/reaction
          method: post
      - http:
          path: /profile
          method: get
      - http:
          path: /twmomo/mysql/query
          method: post
      - http:
          path: /{proxy+}
          method: get

plugins:
  - serverless-prune-plugin
