service: TWProject-Server

provider:
  name: aws
  runtime: nodejs10.x
  memorySize: 2048 # Maxixmum size, type Megabytes
  stage: dev
  region: us-east-2

functions:
  twmomoFunc:
    handler: index.handler
    events:
      - http:
          path: /login
          method: post
      - http:
          path: /register
          method: post
      - http:
          path: /register/detail
          method: post
      - http:
          path: /logging
          method: post
      - http:
          path: /profile
          method: get
      - http:
          path: /concern/rawlist
          method: get
      - http:
          path: /concern/mylist
          method: get
      - http:
          path: /concern/mylist
          method: post
      - http:
          path: /store/review/rating
          method: post
      - http:
          path: /store/review/reaction
          method: post
      - http:
          path: /store/favorite
          method: post
      - http:
          path: /store/favorite
          method: delete
      - http:
          path: /store/favorite
          method: get
      - http:
          path: /store
          method: get
      - http:
          path: /store/favorite/check
          method: get
      - http:
          path: /store/review
          method: get
      - http:
          path: /store/photo
          method: get
      - http:
          path: /store/food
          method: get
      - http:
          path: /twmomo/mysql/query
          method: post
      - http:
          path: /{proxy+}
          method: get

plugins:
  - serverless-prune-plugin
