service: TWProject-Server

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-1

functions:
  twmomoFunc:
    handler: index.handler
    events:
      - http:
          path: /
          method: get
          cors: true
            # origins: 
            #   - http://localhost:8081
            #   - http://localhost:190002

      # - http:
      #     path: pokemon/{id}
      #     method: get
      # - http:
      #     path: pokemon
      #     method: post
      # - http:
      #     path: pokemon/{id}
      #     method: put
      # - http:
      #     path: pokemon/{id}
      #     method: delete